// Part 4 of the complete world countries list (S-Z)
// Following ISO 3166-1 standards with comprehensive regional and language data

import { CountryData } from './country-data';

/**
 * Countries S-Z with comprehensive details
 */
export const countriesSZ: CountryData[] = [
  // S
  {
    name: 'Saint Kitts and Nevis',
    code: 'KN',
    phone_code: '+1-869',
    capital: 'Basseterre',
    region: ['NA', 'CAR', 'CARICOM', 'COMM'],
    subregion: ['CAR'],
    continent_code: 'NA',
    languages: ['en'],
    flag_emoji: '🇰🇳',
    latitude: 17.357822,
    longitude: -62.782998,
  },
  {
    name: 'Saint Lucia',
    code: 'LC',
    phone_code: '+1-758',
    capital: 'Castries',
    region: ['NA', 'CAR', 'CARICOM', 'COMM'],
    subregion: ['CAR'],
    continent_code: 'NA',
    languages: ['en'],
    flag_emoji: '🇱🇨',
    latitude: 13.909444,
    longitude: -60.978893,
  },
  {
    name: 'Saint Vincent and the Grenadines',
    code: 'VC',
    phone_code: '+1-784',
    capital: 'Kingstown',
    region: ['NA', 'CAR', 'CARICOM', 'COMM'],
    subregion: ['CAR'],
    continent_code: 'NA',
    languages: ['en'],
    flag_emoji: '🇻🇨',
    latitude: 12.984305,
    longitude: -61.287228,
  },
  {
    name: 'Samoa',
    code: 'WS',
    phone_code: '+685',
    capital: 'Apia',
    region: ['OC', 'POL', 'COMM'],
    subregion: ['POL'],
    continent_code: 'OC',
    languages: ['sm', 'en'],
    flag_emoji: '🇼🇸',
    latitude: -13.759029,
    longitude: -172.104629,
  },
  {
    name: 'San Marino',
    code: 'SM',
    phone_code: '+378',
    capital: 'San Marino',
    region: ['EU', 'SEU'],
    subregion: ['SEU'],
    continent_code: 'EU',
    languages: ['it'],
    flag_emoji: '🇸🇲',
    latitude: 43.94236,
    longitude: 12.457777,
  },
  {
    name: 'Sao Tome and Principe',
    code: 'ST',
    phone_code: '+239',
    capital: 'São Tomé',
    region: ['AF', 'CAF', 'AU'],
    subregion: ['CAF'],
    continent_code: 'AF',
    languages: ['pt'],
    flag_emoji: '🇸🇹',
    latitude: 0.18636,
    longitude: 6.613081,
  },
  {
    name: 'Saudi Arabia',
    code: 'SA',
    phone_code: '+966',
    capital: 'Riyadh',
    region: ['AS', 'WAS', 'AL', 'GCC', 'OIC', 'OPEC', 'G20'],
    subregion: ['WAS'],
    continent_code: 'AS',
    languages: ['ar'],
    flag_emoji: '🇸🇦',
    latitude: 23.885942,
    longitude: 45.079162,
  },
  {
    name: 'Senegal',
    code: 'SN',
    phone_code: '+221',
    capital: 'Dakar',
    region: ['AF', 'WAF', 'AU', 'OIC'],
    subregion: ['WAF'],
    continent_code: 'AF',
    languages: ['fr'],
    flag_emoji: '🇸🇳',
    latitude: 14.497401,
    longitude: -14.452362,
  },
  {
    name: 'Serbia',
    code: 'RS',
    phone_code: '+381',
    capital: 'Belgrade',
    region: ['EU', 'SEU'],
    subregion: ['SEU'],
    continent_code: 'EU',
    languages: ['sr'],
    flag_emoji: '🇷🇸',
    latitude: 44.016521,
    longitude: 21.005859,
  },
  {
    name: 'Seychelles',
    code: 'SC',
    phone_code: '+248',
    capital: 'Victoria',
    region: ['AF', 'EAF', 'AU', 'SADC', 'COMM'],
    subregion: ['EAF'],
    continent_code: 'AF',
    languages: ['en', 'fr'],
    flag_emoji: '🇸🇨',
    latitude: -4.679574,
    longitude: 55.491977,
  },
  {
    name: 'Sierra Leone',
    code: 'SL',
    phone_code: '+232',
    capital: 'Freetown',
    region: ['AF', 'WAF', 'AU', 'COMM'],
    subregion: ['WAF'],
    continent_code: 'AF',
    languages: ['en'],
    flag_emoji: '🇸🇱',
    latitude: 8.460555,
    longitude: -11.779889,
  },
  {
    name: 'Singapore',
    code: 'SG',
    phone_code: '+65',
    capital: 'Singapore',
    region: ['AS', 'SEA', 'ASEAN', 'COMM'],
    subregion: ['SEA'],
    continent_code: 'AS',
    languages: ['en', 'ms', 'ta', 'zh'],
    flag_emoji: '🇸🇬',
    latitude: 1.352083,
    longitude: 103.819836,
  },
  {
    name: 'Slovakia',
    code: 'SK',
    phone_code: '+421',
    capital: 'Bratislava',
    region: ['EU', 'CEU', 'EUNION', 'NATO', 'OECD'],
    subregion: ['CEU'],
    continent_code: 'EU',
    languages: ['sk'],
    flag_emoji: '🇸🇰',
    latitude: 48.669026,
    longitude: 19.699024,
  },
  {
    name: 'Slovenia',
    code: 'SI',
    phone_code: '+386',
    capital: 'Ljubljana',
    region: ['EU', 'CEU', 'EUNION', 'NATO', 'OECD'],
    subregion: ['CEU'],
    continent_code: 'EU',
    languages: ['sl'],
    flag_emoji: '🇸🇮',
    latitude: 46.151241,
    longitude: 14.995463,
  },
  {
    name: 'Solomon Islands',
    code: 'SB',
    phone_code: '+677',
    capital: 'Honiara',
    region: ['OC', 'MEL', 'COMM'],
    subregion: ['MEL'],
    continent_code: 'OC',
    languages: ['en'],
    flag_emoji: '🇸🇧',
    latitude: -9.64571,
    longitude: 160.156194,
  },
  {
    name: 'Somalia',
    code: 'SO',
    phone_code: '+252',
    capital: 'Mogadishu',
    region: ['AF', 'EAF', 'AU', 'AL', 'OIC'],
    subregion: ['EAF'],
    continent_code: 'AF',
    languages: ['so', 'ar'],
    flag_emoji: '🇸🇴',
    latitude: 5.152149,
    longitude: 46.199616,
  },
  {
    name: 'South Africa',
    code: 'ZA',
    phone_code: '+27',
    capital: 'Pretoria',
    region: ['AF', 'SAF', 'AU', 'SADC', 'COMM', 'BRICS', 'G20'],
    subregion: ['SAF'],
    continent_code: 'AF',
    languages: ['af', 'en', 'nr', 'st', 'ss', 'tn', 'ts', 've', 'xh', 'zu'],
    flag_emoji: '🇿🇦',
    latitude: -30.559482,
    longitude: 22.937506,
  },
  {
    name: 'South Korea',
    code: 'KR',
    phone_code: '+82',
    capital: 'Seoul',
    region: ['AS', 'EAS', 'OECD', 'G20'],
    subregion: ['EAS'],
    continent_code: 'AS',
    languages: ['ko'],
    flag_emoji: '🇰🇷',
    latitude: 35.907757,
    longitude: 127.766922,
  },
  {
    name: 'South Sudan',
    code: 'SS',
    phone_code: '+211',
    capital: 'Juba',
    region: ['AF', 'EAF', 'AU'],
    subregion: ['EAF'],
    continent_code: 'AF',
    languages: ['en'],
    flag_emoji: '🇸🇸',
    latitude: 6.876991,
    longitude: 31.306978,
  },
  {
    name: 'Spain',
    code: 'ES',
    phone_code: '+34',
    capital: 'Madrid',
    region: ['EU', 'SEU', 'EUNION', 'NATO', 'OECD', 'G20'],
    subregion: ['SEU'],
    continent_code: 'EU',
    languages: ['es', 'ca', 'gl', 'eu'],
    flag_emoji: '🇪🇸',
    latitude: 40.463667,
    longitude: -3.74922,
  },
  {
    name: 'Sri Lanka',
    code: 'LK',
    phone_code: '+94',
    capital: 'Colombo',
    region: ['AS', 'SAS', 'COMM'],
    subregion: ['SAS'],
    continent_code: 'AS',
    languages: ['si', 'ta'],
    flag_emoji: '🇱🇰',
    latitude: 7.873054,
    longitude: 80.771797,
  },
  {
    name: 'Sudan',
    code: 'SD',
    phone_code: '+249',
    capital: 'Khartoum',
    region: ['AF', 'NAF', 'AU', 'AL', 'OIC'],
    subregion: ['NAF'],
    continent_code: 'AF',
    languages: ['ar', 'en'],
    flag_emoji: '🇸🇩',
    latitude: 12.862807,
    longitude: 30.217636,
  },
  {
    name: 'Suriname',
    code: 'SR',
    phone_code: '+597',
    capital: 'Paramaribo',
    region: ['SA', 'CARICOM'],
    subregion: ['SA'],
    continent_code: 'SA',
    languages: ['nl'],
    flag_emoji: '🇸🇷',
    latitude: 3.919305,
    longitude: -56.027783,
  },
  {
    name: 'Sweden',
    code: 'SE',
    phone_code: '+46',
    capital: 'Stockholm',
    region: ['EU', 'NEU', 'EUNION', 'OECD'],
    subregion: ['NEU'],
    continent_code: 'EU',
    languages: ['sv'],
    flag_emoji: '🇸🇪',
    latitude: 60.128161,
    longitude: 18.643501,
  },
  {
    name: 'Switzerland',
    code: 'CH',
    phone_code: '+41',
    capital: 'Bern',
    region: ['EU', 'WEU', 'OECD'],
    subregion: ['WEU'],
    continent_code: 'EU',
    languages: ['de', 'fr', 'it', 'rm'],
    flag_emoji: '🇨🇭',
    latitude: 46.818188,
    longitude: 8.227512,
  },
  {
    name: 'Syria',
    code: 'SY',
    phone_code: '+963',
    capital: 'Damascus',
    region: ['AS', 'WAS', 'AL', 'OIC'],
    subregion: ['WAS'],
    continent_code: 'AS',
    languages: ['ar'],
    flag_emoji: '🇸🇾',
    latitude: 34.802075,
    longitude: 38.996815,
  },

  // T
  {
    name: 'Taiwan',
    code: 'TW',
    phone_code: '+886',
    capital: 'Taipei',
    region: ['AS', 'EAS'],
    subregion: ['EAS'],
    continent_code: 'AS',
    languages: ['zh'],
    flag_emoji: '🇹🇼',
    latitude: 23.69781,
    longitude: 120.960515,
  },
  {
    name: 'Tajikistan',
    code: 'TJ',
    phone_code: '+992',
    capital: 'Dushanbe',
    region: ['AS', 'CAS', 'CIS'],
    subregion: ['CAS'],
    continent_code: 'AS',
    languages: ['tg', 'ru'],
    flag_emoji: '🇹🇯',
    latitude: 38.861034,
    longitude: 71.276093,
  },
  {
    name: 'Tanzania',
    code: 'TZ',
    phone_code: '+255',
    capital: 'Dodoma',
    region: ['AF', 'EAF', 'AU', 'SADC', 'COMM'],
    subregion: ['EAF'],
    continent_code: 'AF',
    languages: ['sw', 'en'],
    flag_emoji: '🇹🇿',
    latitude: -6.369028,
    longitude: 34.888822,
  },
  {
    name: 'Thailand',
    code: 'TH',
    phone_code: '+66',
    capital: 'Bangkok',
    region: ['AS', 'SEA', 'ASEAN'],
    subregion: ['SEA'],
    continent_code: 'AS',
    languages: ['th'],
    flag_emoji: '🇹🇭',
    latitude: 15.870032,
    longitude: 100.992541,
  },
  {
    name: 'Timor-Leste',
    code: 'TL',
    phone_code: '+670',
    capital: 'Dili',
    region: ['AS', 'SEA', 'ASEAN'],
    subregion: ['SEA'],
    continent_code: 'AS',
    languages: ['pt'],
    flag_emoji: '🇹🇱',
    latitude: -8.874217,
    longitude: 125.727539,
  },
  {
    name: 'Togo',
    code: 'TG',
    phone_code: '+228',
    capital: 'Lomé',
    region: ['AF', 'WAF', 'AU'],
    subregion: ['WAF'],
    continent_code: 'AF',
    languages: ['fr'],
    flag_emoji: '🇹🇬',
    latitude: 8.619543,
    longitude: 0.824782,
  },
  {
    name: 'Tonga',
    code: 'TO',
    phone_code: '+676',
    capital: "Nuku'alofa",
    region: ['OC', 'POL', 'COMM'],
    subregion: ['POL'],
    continent_code: 'OC',
    languages: ['en', 'to'],
    flag_emoji: '🇹🇴',
    latitude: -21.178986,
    longitude: -175.198242,
  },
  {
    name: 'Trinidad and Tobago',
    code: 'TT',
    phone_code: '+1-868',
    capital: 'Port of Spain',
    region: ['NA', 'CAR', 'CARICOM', 'COMM'],
    subregion: ['CAR'],
    continent_code: 'NA',
    languages: ['en'],
    flag_emoji: '🇹🇹',
    latitude: 10.691803,
    longitude: -61.222503,
  },
  {
    name: 'Tunisia',
    code: 'TN',
    phone_code: '+216',
    capital: 'Tunis',
    region: ['AF', 'NAF', 'AU', 'AL', 'OIC'],
    subregion: ['NAF'],
    continent_code: 'AF',
    languages: ['ar'],
    flag_emoji: '🇹🇳',
    latitude: 33.886917,
    longitude: 9.537499,
  },
  {
    name: 'Turkey',
    code: 'TR',
    phone_code: '+90',
    capital: 'Ankara',
    region: ['AS', 'WAS', 'NATO', 'OECD', 'G20', 'OIC'],
    subregion: ['WAS'],
    continent_code: 'AS',
    languages: ['tr'],
    flag_emoji: '🇹🇷',
    latitude: 38.963745,
    longitude: 35.243322,
  },
  {
    name: 'Turkmenistan',
    code: 'TM',
    phone_code: '+993',
    capital: 'Ashgabat',
    region: ['AS', 'CAS', 'CIS'],
    subregion: ['CAS'],
    continent_code: 'AS',
    languages: ['tk', 'ru'],
    flag_emoji: '🇹🇲',
    latitude: 38.969719,
    longitude: 59.556278,
  },
  {
    name: 'Tuvalu',
    code: 'TV',
    phone_code: '+688',
    capital: 'Funafuti',
    region: ['OC', 'POL', 'COMM'],
    subregion: ['POL'],
    continent_code: 'OC',
    languages: ['en'],
    flag_emoji: '🇹🇻',
    latitude: -7.109535,
    longitude: 177.64933,
  },

  // U
  {
    name: 'Uganda',
    code: 'UG',
    phone_code: '+256',
    capital: 'Kampala',
    region: ['AF', 'EAF', 'AU', 'COMM'],
    subregion: ['EAF'],
    continent_code: 'AF',
    languages: ['en', 'sw'],
    flag_emoji: '🇺🇬',
    latitude: 1.373333,
    longitude: 32.290275,
  },
  {
    name: 'Ukraine',
    code: 'UA',
    phone_code: '+380',
    capital: 'Kyiv',
    region: ['EU', 'EEU'],
    subregion: ['EEU'],
    continent_code: 'EU',
    languages: ['uk'],
    flag_emoji: '🇺🇦',
    latitude: 48.379433,
    longitude: 31.16558,
  },
  {
    name: 'United Arab Emirates',
    code: 'AE',
    phone_code: '+971',
    capital: 'Abu Dhabi',
    region: ['AS', 'WAS', 'AL', 'GCC', 'OIC', 'OPEC'],
    subregion: ['WAS'],
    continent_code: 'AS',
    languages: ['ar'],
    flag_emoji: '🇦🇪',
    latitude: 23.424076,
    longitude: 53.847818,
  },
  {
    name: 'United Kingdom',
    code: 'GB',
    phone_code: '+44',
    capital: 'London',
    region: ['EU', 'NEU', 'NATO', 'OECD', 'G7', 'G20', 'COMM'],
    subregion: ['NEU'],
    continent_code: 'EU',
    languages: ['en'],
    flag_emoji: '🇬🇧',
    latitude: 55.378051,
    longitude: -3.435973,
  },
  {
    name: 'United States',
    code: 'US',
    phone_code: '+1',
    capital: 'Washington, D.C.',
    region: ['NA', 'NAM', 'NATO', 'OECD', 'G7', 'G20'],
    subregion: ['NAM'],
    continent_code: 'NA',
    languages: ['en'],
    flag_emoji: '🇺🇸',
    latitude: 37.09024,
    longitude: -95.712891,
  },
  {
    name: 'Uruguay',
    code: 'UY',
    phone_code: '+598',
    capital: 'Montevideo',
    region: ['SA', 'MERCOSUR'],
    subregion: ['SA'],
    continent_code: 'SA',
    languages: ['es'],
    flag_emoji: '🇺🇾',
    latitude: -32.522779,
    longitude: -55.765835,
  },
  {
    name: 'Uzbekistan',
    code: 'UZ',
    phone_code: '+998',
    capital: 'Tashkent',
    region: ['AS', 'CAS', 'CIS'],
    subregion: ['CAS'],
    continent_code: 'AS',
    languages: ['uz', 'ru'],
    flag_emoji: '🇺🇿',
    latitude: 41.377491,
    longitude: 64.585262,
  },

  // V
  {
    name: 'Vanuatu',
    code: 'VU',
    phone_code: '+678',
    capital: 'Port Vila',
    region: ['OC', 'MEL', 'COMM'],
    subregion: ['MEL'],
    continent_code: 'OC',
    languages: ['bi', 'en', 'fr'],
    flag_emoji: '🇻🇺',
    latitude: -15.376706,
    longitude: 166.959158,
  },
  {
    name: 'Vatican City',
    code: 'VA',
    phone_code: '+39-06',
    capital: 'Vatican City',
    region: ['EU', 'SEU'],
    subregion: ['SEU'],
    continent_code: 'EU',
    languages: ['it', 'la'],
    flag_emoji: '🇻🇦',
    latitude: 41.902916,
    longitude: 12.453389,
  },
  {
    name: 'Venezuela',
    code: 'VE',
    phone_code: '+58',
    capital: 'Caracas',
    region: ['SA', 'OPEC'],
    subregion: ['SA'],
    continent_code: 'SA',
    languages: ['es'],
    flag_emoji: '🇻🇪',
    latitude: 6.42375,
    longitude: -66.58973,
  },
  {
    name: 'Vietnam',
    code: 'VN',
    phone_code: '+84',
    capital: 'Hanoi',
    region: ['AS', 'SEA', 'ASEAN'],
    subregion: ['SEA'],
    continent_code: 'AS',
    languages: ['vi'],
    flag_emoji: '🇻🇳',
    latitude: 14.058324,
    longitude: 108.277199,
  },

  // Y
  {
    name: 'Yemen',
    code: 'YE',
    phone_code: '+967',
    capital: "Sana'a",
    region: ['AS', 'WAS', 'AL', 'OIC'],
    subregion: ['WAS'],
    continent_code: 'AS',
    languages: ['ar'],
    flag_emoji: '🇾🇪',
    latitude: 15.552727,
    longitude: 48.516388,
  },

  // Z
  {
    name: 'Zambia',
    code: 'ZM',
    phone_code: '+260',
    capital: 'Lusaka',
    region: ['AF', 'EAF', 'AU', 'SADC', 'COMM'],
    subregion: ['EAF'],
    continent_code: 'AF',
    languages: ['en'],
    flag_emoji: '🇿🇲',
    latitude: -13.133897,
    longitude: 27.849332,
  },
  {
    name: 'Zimbabwe',
    code: 'ZW',
    phone_code: '+263',
    capital: 'Harare',
    region: ['AF', 'EAF', 'AU', 'SADC', 'COMM'],
    subregion: ['EAF'],
    continent_code: 'AF',
    languages: ['en', 'sn', 'nd'],
    flag_emoji: '🇿🇼',
    latitude: -19.015438,
    longitude: 29.154857,
  }
];
