// Part 2 of the complete world countries list (G-M)
// Following ISO 3166-1 standards with comprehensive regional and language data

import { CountryData } from './country-data';

/**
 * Countries G-M with comprehensive details
 */
export const countriesGM: CountryData[] = [
  // G
  {
    name: 'Gabon',
    code: 'GA',
    phone_code: '+241',
    capital: 'Libreville',
    region: ['AF', 'CAF', 'AU', 'OPEC'],
    subregion: ['CAF'],
    continent_code: 'AF',
    languages: ['fr'],
    flag_emoji: '🇬🇦',
    latitude: -0.803689,
    longitude: 11.609444,
  },
  {
    name: 'Gambia',
    code: 'GM',
    phone_code: '+220',
    capital: 'Banjul',
    region: ['AF', 'WAF', 'AU', 'COMM'],
    subregion: ['WAF'],
    continent_code: 'AF',
    languages: ['en'],
    flag_emoji: '🇬🇲',
    latitude: 13.443182,
    longitude: -15.310139,
  },
  {
    name: 'Georgia',
    code: 'GE',
    phone_code: '+995',
    capital: 'Tbilisi',
    region: ['AS', 'WAS'],
    subregion: ['WAS'],
    continent_code: 'AS',
    languages: ['ka'],
    flag_emoji: '🇬🇪',
    latitude: 42.315407,
    longitude: 43.356892,
  },
  {
    name: 'Germany',
    code: 'DE',
    phone_code: '+49',
    capital: 'Berlin',
    region: ['EU', 'WEU', 'EUNION', 'NATO', 'OECD', 'G7', 'G20'],
    subregion: ['WEU'],
    continent_code: 'EU',
    languages: ['de'],
    flag_emoji: '🇩🇪',
    latitude: 51.165691,
    longitude: 10.451526,
  },
  {
    name: 'Ghana',
    code: 'GH',
    phone_code: '+233',
    capital: 'Accra',
    region: ['AF', 'WAF', 'AU', 'COMM'],
    subregion: ['WAF'],
    continent_code: 'AF',
    languages: ['en'],
    flag_emoji: '🇬🇭',
    latitude: 7.946527,
    longitude: -1.023194,
  },
  {
    name: 'Greece',
    code: 'GR',
    phone_code: '+30',
    capital: 'Athens',
    region: ['EU', 'SEU', 'EUNION', 'NATO', 'OECD'],
    subregion: ['SEU'],
    continent_code: 'EU',
    languages: ['el'],
    flag_emoji: '🇬🇷',
    latitude: 39.074208,
    longitude: 21.824312,
  },
  {
    name: 'Grenada',
    code: 'GD',
    phone_code: '+1-473',
    capital: "St. George's",
    region: ['NA', 'CAR', 'CARICOM', 'COMM'],
    subregion: ['CAR'],
    continent_code: 'NA',
    languages: ['en'],
    flag_emoji: '🇬🇩',
    latitude: 12.262776,
    longitude: -61.604171,
  },
  {
    name: 'Guatemala',
    code: 'GT',
    phone_code: '+502',
    capital: 'Guatemala City',
    region: ['NA', 'CAM'],
    subregion: ['CAM'],
    continent_code: 'NA',
    languages: ['es'],
    flag_emoji: '🇬🇹',
    latitude: 15.783471,
    longitude: -90.230759,
  },
  {
    name: 'Guinea',
    code: 'GN',
    phone_code: '+224',
    capital: 'Conakry',
    region: ['AF', 'WAF', 'AU'],
    subregion: ['WAF'],
    continent_code: 'AF',
    languages: ['fr', 'ff'],
    flag_emoji: '🇬🇳',
    latitude: 9.945587,
    longitude: -9.696645,
  },
  {
    name: 'Guinea-Bissau',
    code: 'GW',
    phone_code: '+245',
    capital: 'Bissau',
    region: ['AF', 'WAF', 'AU'],
    subregion: ['WAF'],
    continent_code: 'AF',
    languages: ['pt'],
    flag_emoji: '🇬🇼',
    latitude: 11.803749,
    longitude: -15.180413,
  },
  {
    name: 'Guyana',
    code: 'GY',
    phone_code: '+592',
    capital: 'Georgetown',
    region: ['SA', 'CARICOM', 'COMM'],
    subregion: ['SA'],
    continent_code: 'SA',
    languages: ['en'],
    flag_emoji: '🇬🇾',
    latitude: 4.860416,
    longitude: -58.93018,
  },

  // H
  {
    name: 'Haiti',
    code: 'HT',
    phone_code: '+509',
    capital: 'Port-au-Prince',
    region: ['NA', 'CAR', 'CARICOM'],
    subregion: ['CAR'],
    continent_code: 'NA',
    languages: ['fr', 'ht'],
    flag_emoji: '🇭🇹',
    latitude: 18.971187,
    longitude: -72.285215,
  },
  {
    name: 'Honduras',
    code: 'HN',
    phone_code: '+504',
    capital: 'Tegucigalpa',
    region: ['NA', 'CAM'],
    subregion: ['CAM'],
    continent_code: 'NA',
    languages: ['es'],
    flag_emoji: '🇭🇳',
    latitude: 15.199999,
    longitude: -86.241905,
  },
  {
    name: 'Hungary',
    code: 'HU',
    phone_code: '+36',
    capital: 'Budapest',
    region: ['EU', 'CEU', 'EUNION', 'NATO', 'OECD'],
    subregion: ['CEU'],
    continent_code: 'EU',
    languages: ['hu'],
    flag_emoji: '🇭🇺',
    latitude: 47.162494,
    longitude: 19.503304,
  },

  // I
  {
    name: 'Iceland',
    code: 'IS',
    phone_code: '+354',
    capital: 'Reykjavik',
    region: ['EU', 'NEU', 'NATO', 'OECD'],
    subregion: ['NEU'],
    continent_code: 'EU',
    languages: ['is'],
    flag_emoji: '🇮🇸',
    latitude: 64.963051,
    longitude: -19.020835,
  },
  {
    name: 'India',
    code: 'IN',
    phone_code: '+91',
    capital: 'New Delhi',
    region: ['AS', 'SAS', 'BRICS', 'COMM', 'G20'],
    subregion: ['SAS'],
    continent_code: 'AS',
    languages: ['hi', 'en'],
    flag_emoji: '🇮🇳',
    latitude: 20.593684,
    longitude: 78.96288,
  },
  {
    name: 'Indonesia',
    code: 'ID',
    phone_code: '+62',
    capital: 'Jakarta',
    region: ['AS', 'SEA', 'ASEAN', 'G20', 'OIC'],
    subregion: ['SEA'],
    continent_code: 'AS',
    languages: ['id'],
    flag_emoji: '🇮🇩',
    latitude: -0.789275,
    longitude: 113.921327,
  },
  {
    name: 'Iran',
    code: 'IR',
    phone_code: '+98',
    capital: 'Tehran',
    region: ['AS', 'WAS', 'OIC'],
    subregion: ['WAS'],
    continent_code: 'AS',
    languages: ['fa'],
    flag_emoji: '🇮🇷',
    latitude: 32.427908,
    longitude: 53.688046,
  },
  {
    name: 'Iraq',
    code: 'IQ',
    phone_code: '+964',
    capital: 'Baghdad',
    region: ['AS', 'WAS', 'AL', 'OIC'],
    subregion: ['WAS'],
    continent_code: 'AS',
    languages: ['ar', 'ku'],
    flag_emoji: '🇮🇶',
    latitude: 33.223191,
    longitude: 43.679291,
  },
  {
    name: 'Ireland',
    code: 'IE',
    phone_code: '+353',
    capital: 'Dublin',
    region: ['EU', 'NEU', 'EUNION', 'OECD'],
    subregion: ['NEU'],
    continent_code: 'EU',
    languages: ['ga', 'en'],
    flag_emoji: '🇮🇪',
    latitude: 53.41291,
    longitude: -8.24389,
  },
  {
    name: 'Israel',
    code: 'IL',
    phone_code: '+972',
    capital: 'Jerusalem',
    region: ['AS', 'WAS', 'OECD'],
    subregion: ['WAS'],
    continent_code: 'AS',
    languages: ['he', 'ar'],
    flag_emoji: '🇮🇱',
    latitude: 31.046051,
    longitude: 34.851612,
  },
  {
    name: 'Italy',
    code: 'IT',
    phone_code: '+39',
    capital: 'Rome',
    region: ['EU', 'SEU', 'EUNION', 'NATO', 'OECD', 'G7', 'G20'],
    subregion: ['SEU'],
    continent_code: 'EU',
    languages: ['it'],
    flag_emoji: '🇮🇹',
    latitude: 41.87194,
    longitude: 12.56738,
  },

  // J
  {
    name: 'Jamaica',
    code: 'JM',
    phone_code: '+1-876',
    capital: 'Kingston',
    region: ['NA', 'CAR', 'CARICOM', 'COMM'],
    subregion: ['CAR'],
    continent_code: 'NA',
    languages: ['en'],
    flag_emoji: '🇯🇲',
    latitude: 18.109581,
    longitude: -77.297508,
  },
  {
    name: 'Japan',
    code: 'JP',
    phone_code: '+81',
    capital: 'Tokyo',
    region: ['AS', 'EAS', 'OECD', 'G7', 'G20'],
    subregion: ['EAS'],
    continent_code: 'AS',
    languages: ['ja'],
    flag_emoji: '🇯🇵',
    latitude: 36.204824,
    longitude: 138.252924,
  },
  {
    name: 'Jordan',
    code: 'JO',
    phone_code: '+962',
    capital: 'Amman',
    region: ['AS', 'WAS', 'AL', 'OIC'],
    subregion: ['WAS'],
    continent_code: 'AS',
    languages: ['ar'],
    flag_emoji: '🇯🇴',
    latitude: 30.585164,
    longitude: 36.238414,
  },

  // K
  {
    name: 'Kazakhstan',
    code: 'KZ',
    phone_code: '+7',
    capital: 'Nur-Sultan',
    region: ['AS', 'CAS', 'CIS'],
    subregion: ['CAS'],
    continent_code: 'AS',
    languages: ['kk', 'ru'],
    flag_emoji: '🇰🇿',
    latitude: 48.019573,
    longitude: 66.923684,
  },
  {
    name: 'Kenya',
    code: 'KE',
    phone_code: '+254',
    capital: 'Nairobi',
    region: ['AF', 'EAF', 'AU', 'COMM'],
    subregion: ['EAF'],
    continent_code: 'AF',
    languages: ['en', 'sw'],
    flag_emoji: '🇰🇪',
    latitude: -0.023559,
    longitude: 37.906193,
  },
  {
    name: 'Kiribati',
    code: 'KI',
    phone_code: '+686',
    capital: 'Tarawa',
    region: ['OC', 'MIC', 'COMM'],
    subregion: ['MIC'],
    continent_code: 'OC',
    languages: ['en'],
    flag_emoji: '🇰🇮',
    latitude: -3.370417,
    longitude: -168.734039,
  },
  {
    name: 'Kuwait',
    code: 'KW',
    phone_code: '+965',
    capital: 'Kuwait City',
    region: ['AS', 'WAS', 'AL', 'GCC', 'OIC'],
    subregion: ['WAS'],
    continent_code: 'AS',
    languages: ['ar'],
    flag_emoji: '🇰🇼',
    latitude: 29.31166,
    longitude: 47.481766,
  },
  {
    name: 'Kyrgyzstan',
    code: 'KG',
    phone_code: '+996',
    capital: 'Bishkek',
    region: ['AS', 'CAS', 'CIS'],
    subregion: ['CAS'],
    continent_code: 'AS',
    languages: ['ky', 'ru'],
    flag_emoji: '🇰🇬',
    latitude: 41.20438,
    longitude: 74.766098,
  },

  // L
  {
    name: 'Laos',
    code: 'LA',
    phone_code: '+856',
    capital: 'Vientiane',
    region: ['AS', 'SEA', 'ASEAN'],
    subregion: ['SEA'],
    continent_code: 'AS',
    languages: ['lo'],
    flag_emoji: '🇱🇦',
    latitude: 19.85627,
    longitude: 102.495496,
  },
  {
    name: 'Latvia',
    code: 'LV',
    phone_code: '+371',
    capital: 'Riga',
    region: ['EU', 'NEU', 'EUNION', 'NATO', 'OECD'],
    subregion: ['NEU'],
    continent_code: 'EU',
    languages: ['lv'],
    flag_emoji: '🇱🇻',
    latitude: 56.879635,
    longitude: 24.603189,
  },
  {
    name: 'Lebanon',
    code: 'LB',
    phone_code: '+961',
    capital: 'Beirut',
    region: ['AS', 'WAS', 'AL', 'OIC'],
    subregion: ['WAS'],
    continent_code: 'AS',
    languages: ['ar', 'fr'],
    flag_emoji: '🇱🇧',
    latitude: 33.854721,
    longitude: 35.862285,
  },
  {
    name: 'Lesotho',
    code: 'LS',
    phone_code: '+266',
    capital: 'Maseru',
    region: ['AF', 'SAF', 'AU', 'SADC', 'COMM'],
    subregion: ['SAF'],
    continent_code: 'AF',
    languages: ['en', 'st'],
    flag_emoji: '🇱🇸',
    latitude: -29.609988,
    longitude: 28.233608,
  },
  {
    name: 'Liberia',
    code: 'LR',
    phone_code: '+231',
    capital: 'Monrovia',
    region: ['AF', 'WAF', 'AU'],
    subregion: ['WAF'],
    continent_code: 'AF',
    languages: ['en'],
    flag_emoji: '🇱🇷',
    latitude: 6.428055,
    longitude: -9.429499,
  },
  {
    name: 'Libya',
    code: 'LY',
    phone_code: '+218',
    capital: 'Tripoli',
    region: ['AF', 'NAF', 'AU', 'AL', 'OIC', 'OPEC'],
    subregion: ['NAF'],
    continent_code: 'AF',
    languages: ['ar'],
    flag_emoji: '🇱🇾',
    latitude: 26.3351,
    longitude: 17.228331,
  },
  {
    name: 'Liechtenstein',
    code: 'LI',
    phone_code: '+423',
    capital: 'Vaduz',
    region: ['EU', 'WEU'],
    subregion: ['WEU'],
    continent_code: 'EU',
    languages: ['de'],
    flag_emoji: '🇱🇮',
    latitude: 47.166,
    longitude: 9.555373,
  },
  {
    name: 'Lithuania',
    code: 'LT',
    phone_code: '+370',
    capital: 'Vilnius',
    region: ['EU', 'NEU', 'EUNION', 'NATO', 'OECD'],
    subregion: ['NEU'],
    continent_code: 'EU',
    languages: ['lt'],
    flag_emoji: '🇱🇹',
    latitude: 55.169438,
    longitude: 23.881275,
  },
  {
    name: 'Luxembourg',
    code: 'LU',
    phone_code: '+352',
    capital: 'Luxembourg',
    region: ['EU', 'WEU', 'EUNION', 'NATO', 'OECD'],
    subregion: ['WEU'],
    continent_code: 'EU',
    languages: ['lb', 'fr', 'de'],
    flag_emoji: '🇱🇺',
    latitude: 49.815273,
    longitude: 6.129583,
  },

  // M
  {
    name: 'Madagascar',
    code: 'MG',
    phone_code: '+261',
    capital: 'Antananarivo',
    region: ['AF', 'EAF', 'AU', 'SADC'],
    subregion: ['EAF'],
    continent_code: 'AF',
    languages: ['fr', 'mg'],
    flag_emoji: '🇲🇬',
    latitude: -18.766947,
    longitude: 46.869107,
  },
  {
    name: 'Malawi',
    code: 'MW',
    phone_code: '+265',
    capital: 'Lilongwe',
    region: ['AF', 'EAF', 'AU', 'SADC', 'COMM'],
    subregion: ['EAF'],
    continent_code: 'AF',
    languages: ['en', 'ny'],
    flag_emoji: '🇲🇼',
    latitude: -13.254308,
    longitude: 34.301525,
  },
  {
    name: 'Malaysia',
    code: 'MY',
    phone_code: '+60',
    capital: 'Kuala Lumpur',
    region: ['AS', 'SEA', 'ASEAN', 'COMM', 'OIC'],
    subregion: ['SEA'],
    continent_code: 'AS',
    languages: ['ms'],
    flag_emoji: '🇲🇾',
    latitude: 4.210484,
    longitude: 101.975766,
  },
  {
    name: 'Maldives',
    code: 'MV',
    phone_code: '+960',
    capital: 'Malé',
    region: ['AS', 'SAS', 'COMM', 'OIC'],
    subregion: ['SAS'],
    continent_code: 'AS',
    languages: ['dv'],
    flag_emoji: '🇲🇻',
    latitude: 3.202778,
    longitude: 73.22068,
  },
  {
    name: 'Mali',
    code: 'ML',
    phone_code: '+223',
    capital: 'Bamako',
    region: ['AF', 'WAF', 'AU', 'OIC'],
    subregion: ['WAF'],
    continent_code: 'AF',
    languages: ['fr'],
    flag_emoji: '🇲🇱',
    latitude: 17.570692,
    longitude: -3.996166,
  },
  {
    name: 'Malta',
    code: 'MT',
    phone_code: '+356',
    capital: 'Valletta',
    region: ['EU', 'SEU', 'EUNION', 'COMM'],
    subregion: ['SEU'],
    continent_code: 'EU',
    languages: ['mt', 'en'],
    flag_emoji: '🇲🇹',
    latitude: 35.937496,
    longitude: 14.375416,
  },
  {
    name: 'Marshall Islands',
    code: 'MH',
    phone_code: '+692',
    capital: 'Majuro',
    region: ['OC', 'MIC'],
    subregion: ['MIC'],
    continent_code: 'OC',
    languages: ['en', 'mh'],
    flag_emoji: '🇲🇭',
    latitude: 7.131474,
    longitude: 171.184478,
  },
  {
    name: 'Mauritania',
    code: 'MR',
    phone_code: '+222',
    capital: 'Nouakchott',
    region: ['AF', 'WAF', 'AU', 'AL', 'OIC'],
    subregion: ['WAF'],
    continent_code: 'AF',
    languages: ['ar'],
    flag_emoji: '🇲🇷',
    latitude: 21.00789,
    longitude: -10.940835,
  },
  {
    name: 'Mauritius',
    code: 'MU',
    phone_code: '+230',
    capital: 'Port Louis',
    region: ['AF', 'EAF', 'AU', 'SADC', 'COMM'],
    subregion: ['EAF'],
    continent_code: 'AF',
    languages: ['en', 'fr'],
    flag_emoji: '🇲🇺',
    latitude: -20.348404,
    longitude: 57.552152,
  },
  {
    name: 'Mexico',
    code: 'MX',
    phone_code: '+52',
    capital: 'Mexico City',
    region: ['NA', 'CAM', 'NAFTA', 'OECD', 'G20'],
    subregion: ['CAM'],
    continent_code: 'NA',
    languages: ['es'],
    flag_emoji: '🇲🇽',
    latitude: 23.634501,
    longitude: -102.552784,
  },
  {
    name: 'Micronesia',
    code: 'FM',
    phone_code: '+691',
    capital: 'Palikir',
    region: ['OC', 'MIC'],
    subregion: ['MIC'],
    continent_code: 'OC',
    languages: ['en'],
    flag_emoji: '🇫🇲',
    latitude: 7.425554,
    longitude: 150.550812,
  },
  {
    name: 'Moldova',
    code: 'MD',
    phone_code: '+373',
    capital: 'Chisinau',
    region: ['EU', 'EEU', 'CIS'],
    subregion: ['EEU'],
    continent_code: 'EU',
    languages: ['ro'],
    flag_emoji: '🇲🇩',
    latitude: 47.411631,
    longitude: 28.369885,
  },
  {
    name: 'Monaco',
    code: 'MC',
    phone_code: '+377',
    capital: 'Monaco',
    region: ['EU', 'WEU'],
    subregion: ['WEU'],
    continent_code: 'EU',
    languages: ['fr'],
    flag_emoji: '🇲🇨',
    latitude: 43.750298,
    longitude: 7.412841,
  },
  {
    name: 'Mongolia',
    code: 'MN',
    phone_code: '+976',
    capital: 'Ulaanbaatar',
    region: ['AS', 'EAS'],
    subregion: ['EAS'],
    continent_code: 'AS',
    languages: ['mn'],
    flag_emoji: '🇲🇳',
    latitude: 46.862496,
    longitude: 103.846656,
  },
  {
    name: 'Montenegro',
    code: 'ME',
    phone_code: '+382',
    capital: 'Podgorica',
    region: ['EU', 'SEU', 'NATO'],
    subregion: ['SEU'],
    continent_code: 'EU',
    languages: ['sr', 'bs', 'sq', 'hr'],
    flag_emoji: '🇲🇪',
    latitude: 42.708678,
    longitude: 19.37439,
  },
  {
    name: 'Morocco',
    code: 'MA',
    phone_code: '+212',
    capital: 'Rabat',
    region: ['AF', 'NAF', 'AU', 'AL', 'OIC'],
    subregion: ['NAF'],
    continent_code: 'AF',
    languages: ['ar'],
    flag_emoji: '🇲🇦',
    latitude: 31.791702,
    longitude: -7.09262,
  },
  {
    name: 'Mozambique',
    code: 'MZ',
    phone_code: '+258',
    capital: 'Maputo',
    region: ['AF', 'EAF', 'AU', 'SADC', 'COMM'],
    subregion: ['EAF'],
    continent_code: 'AF',
    languages: ['pt'],
    flag_emoji: '🇲🇿',
    latitude: -18.665695,
    longitude: 35.529562,
  },
  {
    name: 'Myanmar',
    code: 'MM',
    phone_code: '+95',
    capital: 'Naypyidaw',
    region: ['AS', 'SEA', 'ASEAN'],
    subregion: ['SEA'],
    continent_code: 'AS',
    languages: ['my'],
    flag_emoji: '🇲🇲',
    latitude: 21.913965,
    longitude: 95.956223,
  }
];
