// Complete list of countries in the world
// Following ISO 3166-1 standards with comprehensive regional and language data

import { CountryData } from './country-data';

/**
 * Comprehensive list of all countries in the world
 * Including:
 * - ISO codes
 * - Capital cities
 * - Region affiliations
 * - Languages
 * - Geographical coordinates
 */
export const allCountries: CountryData[] = [
  // A
  {
    name: 'Afghanistan',
    code: 'AF',
    phone_code: '+93',
    capital: 'Kabul',
    region: ['AS', 'SAS'],
    subregion: ['SAS'],
    continent_code: 'AS',
    languages: ['ps', 'fa'],
    flag_emoji: '🇦🇫',
    latitude: 33.93911,
    longitude: 67.709953,
  },
  {
    name: 'Albania',
    code: 'AL',
    phone_code: '+355',
    capital: 'Tirana',
    region: ['EU', 'SEU', 'NATO'],
    subregion: ['SEU'],
    continent_code: 'EU',
    languages: ['sq'],
    flag_emoji: '🇦🇱',
    latitude: 41.153332,
    longitude: 20.168331,
  },
  {
    name: 'Algeria',
    code: 'DZ',
    phone_code: '+213',
    capital: 'Algiers',
    region: ['AF', 'NAF', 'AU', 'AL', 'OPEC'],
    subregion: ['NAF'],
    continent_code: 'AF',
    languages: ['ar'],
    flag_emoji: '🇩🇿',
    latitude: 28.033886,
    longitude: 1.659626,
  },
  {
    name: 'Andorra',
    code: 'AD',
    phone_code: '+376',
    capital: 'Andorra la Vella',
    region: ['EU', 'SEU'],
    subregion: ['SEU'],
    continent_code: 'EU',
    languages: ['ca'],
    flag_emoji: '🇦🇩',
    latitude: 42.546245,
    longitude: 1.601554,
  },
  {
    name: 'Angola',
    code: 'AO',
    phone_code: '+244',
    capital: 'Luanda',
    region: ['AF', 'CAF', 'AU', 'SADC'],
    subregion: ['CAF'],
    continent_code: 'AF',
    languages: ['pt'],
    flag_emoji: '🇦🇴',
    latitude: -11.202692,
    longitude: 17.873887,
  },
  {
    name: 'Antigua and Barbuda',
    code: 'AG',
    phone_code: '+1-268',
    capital: "Saint John's",
    region: ['NA', 'CAR', 'CARICOM', 'COMM'],
    subregion: ['CAR'],
    continent_code: 'NA',
    languages: ['en'],
    flag_emoji: '🇦🇬',
    latitude: 17.060816,
    longitude: -61.796428,
  },
  {
    name: 'Argentina',
    code: 'AR',
    phone_code: '+54',
    capital: 'Buenos Aires',
    region: ['SA', 'MERCOSUR', 'G20'],
    subregion: ['SA'],
    continent_code: 'SA',
    languages: ['es', 'gn'],
    flag_emoji: '🇦🇷',
    latitude: -38.416097,
    longitude: -63.616672,
  },
  {
    name: 'Armenia',
    code: 'AM',
    phone_code: '+374',
    capital: 'Yerevan',
    region: ['AS', 'WAS', 'CIS'],
    subregion: ['WAS'],
    continent_code: 'AS',
    languages: ['hy', 'ru'],
    flag_emoji: '🇦🇲',
    latitude: 40.069099,
    longitude: 45.038189,
  },
  {
    name: 'Australia',
    code: 'AU',
    phone_code: '+61',
    capital: 'Canberra',
    region: ['OC', 'OECD', 'COMM', 'G20', 'AUSNZ'],
    subregion: ['OC'],
    continent_code: 'OC',
    languages: ['en'],
    flag_emoji: '🇦🇺',
    latitude: -25.274398,
    longitude: 133.775136,
  },
  {
    name: 'Austria',
    code: 'AT',
    phone_code: '+43',
    capital: 'Vienna',
    region: ['EU', 'CEU', 'EUNION', 'OECD'],
    subregion: ['CEU'],
    continent_code: 'EU',
    languages: ['de'],
    flag_emoji: '🇦🇹',
    latitude: 47.516231,
    longitude: 14.550072,
  },
  {
    name: 'Azerbaijan',
    code: 'AZ',
    phone_code: '+994',
    capital: 'Baku',
    region: ['AS', 'WAS', 'CIS'],
    subregion: ['WAS'],
    continent_code: 'AS',
    languages: ['az', 'ru'],
    flag_emoji: '🇦🇿',
    latitude: 40.143105,
    longitude: 47.576927,
  },

  // B
  {
    name: 'Bahamas',
    code: 'BS',
    phone_code: '+1-242',
    capital: 'Nassau',
    region: ['NA', 'CAR', 'CARICOM', 'COMM'],
    subregion: ['CAR'],
    continent_code: 'NA',
    languages: ['en'],
    flag_emoji: '🇧🇸',
    latitude: 25.03428,
    longitude: -77.39628,
  },
  {
    name: 'Bahrain',
    code: 'BH',
    phone_code: '+973',
    capital: 'Manama',
    region: ['AS', 'WAS', 'AL', 'GCC', 'OIC'],
    subregion: ['WAS'],
    continent_code: 'AS',
    languages: ['ar'],
    flag_emoji: '🇧🇭',
    latitude: 25.930414,
    longitude: 50.637772,
  },
  {
    name: 'Bangladesh',
    code: 'BD',
    phone_code: '+880',
    capital: 'Dhaka',
    region: ['AS', 'SAS', 'COMM', 'OIC'],
    subregion: ['SAS'],
    continent_code: 'AS',
    languages: ['bn'],
    flag_emoji: '🇧🇩',
    latitude: 23.684994,
    longitude: 90.356331,
  },
  {
    name: 'Barbados',
    code: 'BB',
    phone_code: '+1-246',
    capital: 'Bridgetown',
    region: ['NA', 'CAR', 'CARICOM', 'COMM'],
    subregion: ['CAR'],
    continent_code: 'NA',
    languages: ['en'],
    flag_emoji: '🇧🇧',
    latitude: 13.193887,
    longitude: -59.543198,
  },
  {
    name: 'Belarus',
    code: 'BY',
    phone_code: '+375',
    capital: 'Minsk',
    region: ['EU', 'EEU', 'CIS'],
    subregion: ['EEU'],
    continent_code: 'EU',
    languages: ['be', 'ru'],
    flag_emoji: '🇧🇾',
    latitude: 53.709807,
    longitude: 27.953389,
  },
  {
    name: 'Belgium',
    code: 'BE',
    phone_code: '+32',
    capital: 'Brussels',
    region: ['EU', 'WEU', 'EUNION', 'NATO', 'OECD'],
    subregion: ['WEU'],
    continent_code: 'EU',
    languages: ['nl', 'fr', 'de'],
    flag_emoji: '🇧🇪',
    latitude: 50.503887,
    longitude: 4.469936,
  },
  {
    name: 'Belize',
    code: 'BZ',
    phone_code: '+501',
    capital: 'Belmopan',
    region: ['NA', 'CAM', 'CARICOM', 'COMM'],
    subregion: ['CAM'],
    continent_code: 'NA',
    languages: ['en', 'es'],
    flag_emoji: '🇧🇿',
    latitude: 17.189877,
    longitude: -88.49765,
  },
  {
    name: 'Benin',
    code: 'BJ',
    phone_code: '+229',
    capital: 'Porto-Novo',
    region: ['AF', 'WAF', 'AU'],
    subregion: ['WAF'],
    continent_code: 'AF',
    languages: ['fr'],
    flag_emoji: '🇧🇯',
    latitude: 9.30769,
    longitude: 2.315834,
  },
  {
    name: 'Bhutan',
    code: 'BT',
    phone_code: '+975',
    capital: 'Thimphu',
    region: ['AS', 'SAS'],
    subregion: ['SAS'],
    continent_code: 'AS',
    languages: ['dz'],
    flag_emoji: '🇧🇹',
    latitude: 27.514162,
    longitude: 90.433601,
  },
  {
    name: 'Bolivia',
    code: 'BO',
    phone_code: '+591',
    capital: 'Sucre',
    region: ['SA', 'MERCOSUR'],
    subregion: ['SA'],
    continent_code: 'SA',
    languages: ['es', 'ay', 'qu'],
    flag_emoji: '🇧🇴',
    latitude: -16.290154,
    longitude: -63.588653,
  },
  {
    name: 'Bosnia and Herzegovina',
    code: 'BA',
    phone_code: '+387',
    capital: 'Sarajevo',
    region: ['EU', 'SEU'],
    subregion: ['SEU'],
    continent_code: 'EU',
    languages: ['bs', 'hr', 'sr'],
    flag_emoji: '🇧🇦',
    latitude: 43.915886,
    longitude: 17.679076,
  },
  {
    name: 'Botswana',
    code: 'BW',
    phone_code: '+267',
    capital: 'Gaborone',
    region: ['AF', 'SAF', 'AU', 'SADC', 'COMM'],
    subregion: ['SAF'],
    continent_code: 'AF',
    languages: ['en', 'tn'],
    flag_emoji: '🇧🇼',
    latitude: -22.328474,
    longitude: 24.684866,
  },
  {
    name: 'Brazil',
    code: 'BR',
    phone_code: '+55',
    capital: 'Brasília',
    region: ['SA', 'MERCOSUR', 'BRICS', 'G20'],
    subregion: ['SA'],
    continent_code: 'SA',
    languages: ['pt'],
    flag_emoji: '🇧🇷',
    latitude: -14.235004,
    longitude: -51.92528,
  },
  {
    name: 'Brunei',
    code: 'BN',
    phone_code: '+673',
    capital: 'Bandar Seri Begawan',
    region: ['AS', 'SEA', 'ASEAN'],
    subregion: ['SEA'],
    continent_code: 'AS',
    languages: ['ms'],
    flag_emoji: '🇧🇳',
    latitude: 4.535277,
    longitude: 114.727669,
  },
  {
    name: 'Bulgaria',
    code: 'BG',
    phone_code: '+359',
    capital: 'Sofia',
    region: ['EU', 'EEU', 'EUNION', 'NATO'],
    subregion: ['EEU'],
    continent_code: 'EU',
    languages: ['bg'],
    flag_emoji: '🇧🇬',
    latitude: 42.733883,
    longitude: 25.48583,
  },
  {
    name: 'Burkina Faso',
    code: 'BF',
    phone_code: '+226',
    capital: 'Ouagadougou',
    region: ['AF', 'WAF', 'AU'],
    subregion: ['WAF'],
    continent_code: 'AF',
    languages: ['fr', 'ff'],
    flag_emoji: '🇧🇫',
    latitude: 12.238333,
    longitude: -1.561593,
  },
  {
    name: 'Burundi',
    code: 'BI',
    phone_code: '+257',
    capital: 'Gitega',
    region: ['AF', 'EAF', 'AU'],
    subregion: ['EAF'],
    continent_code: 'AF',
    languages: ['fr', 'rn'],
    flag_emoji: '🇧🇮',
    latitude: -3.373056,
    longitude: 29.918886,
  },

  // C
  {
    name: 'Cambodia',
    code: 'KH',
    phone_code: '+855',
    capital: 'Phnom Penh',
    region: ['AS', 'SEA', 'ASEAN'],
    subregion: ['SEA'],
    continent_code: 'AS',
    languages: ['km'],
    flag_emoji: '🇰🇭',
    latitude: 12.565679,
    longitude: 104.990963,
  },
  {
    name: 'Cameroon',
    code: 'CM',
    phone_code: '+237',
    capital: 'Yaoundé',
    region: ['AF', 'CAF', 'AU'],
    subregion: ['CAF'],
    continent_code: 'AF',
    languages: ['en', 'fr'],
    flag_emoji: '🇨🇲',
    latitude: 7.369722,
    longitude: 12.354722,
  },
  {
    name: 'Canada',
    code: 'CA',
    phone_code: '+1',
    capital: 'Ottawa',
    region: ['NA', 'NAM', 'OECD', 'G7', 'COMM', 'NATO'],
    subregion: ['NAM'],
    continent_code: 'NA',
    languages: ['en', 'fr'],
    flag_emoji: '🇨🇦',
    latitude: 56.130366,
    longitude: -106.346771,
  },
  {
    name: 'Cape Verde',
    code: 'CV',
    phone_code: '+238',
    capital: 'Praia',
    region: ['AF', 'WAF', 'AU'],
    subregion: ['WAF'],
    continent_code: 'AF',
    languages: ['pt'],
    flag_emoji: '🇨🇻',
    latitude: 16.002082,
    longitude: -24.013197,
  },
  {
    name: 'Central African Republic',
    code: 'CF',
    phone_code: '+236',
    capital: 'Bangui',
    region: ['AF', 'CAF', 'AU'],
    subregion: ['CAF'],
    continent_code: 'AF',
    languages: ['fr', 'sg'],
    flag_emoji: '🇨🇫',
    latitude: 6.611111,
    longitude: 20.939444,
  },
  {
    name: 'Chad',
    code: 'TD',
    phone_code: '+235',
    capital: "N'Djamena",
    region: ['AF', 'CAF', 'AU'],
    subregion: ['CAF'],
    continent_code: 'AF',
    languages: ['fr', 'ar'],
    flag_emoji: '🇹🇩',
    latitude: 15.454166,
    longitude: 18.732207,
  },
  {
    name: 'Chile',
    code: 'CL',
    phone_code: '+56',
    capital: 'Santiago',
    region: ['SA', 'OECD'],
    subregion: ['SA'],
    continent_code: 'SA',
    languages: ['es'],
    flag_emoji: '🇨🇱',
    latitude: -35.675147,
    longitude: -71.542969,
  },
  {
    name: 'China',
    code: 'CN',
    phone_code: '+86',
    capital: 'Beijing',
    region: ['AS', 'EAS', 'BRICS', 'G20'],
    subregion: ['EAS'],
    continent_code: 'AS',
    languages: ['zh'],
    flag_emoji: '🇨🇳',
    latitude: 35.86166,
    longitude: 104.195397,
  },
  {
    name: 'Colombia',
    code: 'CO',
    phone_code: '+57',
    capital: 'Bogotá',
    region: ['SA', 'AND'],
    subregion: ['SA'],
    continent_code: 'SA',
    languages: ['es'],
    flag_emoji: '🇨🇴',
    latitude: 4.570868,
    longitude: -74.297333,
  },
  {
    name: 'Comoros',
    code: 'KM',
    phone_code: '+269',
    capital: 'Moroni',
    region: ['AF', 'EAF', 'AU', 'AL', 'OIC'],
    subregion: ['EAF'],
    continent_code: 'AF',
    languages: ['ar', 'fr'],
    flag_emoji: '🇰🇲',
    latitude: -11.875001,
    longitude: 43.872219,
  },
  {
    name: 'Congo (Republic)',
    code: 'CG',
    phone_code: '+242',
    capital: 'Brazzaville',
    region: ['AF', 'CAF', 'AU'],
    subregion: ['CAF'],
    continent_code: 'AF',
    languages: ['fr', 'ln'],
    flag_emoji: '🇨🇬',
    latitude: -0.228021,
    longitude: 15.827659,
  },
  {
    name: 'Congo (Democratic Republic)',
    code: 'CD',
    phone_code: '+243',
    capital: 'Kinshasa',
    region: ['AF', 'CAF', 'AU', 'SADC'],
    subregion: ['CAF'],
    continent_code: 'AF',
    languages: ['fr', 'ln', 'kg', 'sw'],
    flag_emoji: '🇨🇩',
    latitude: -4.038333,
    longitude: 21.758664,
  },
  {
    name: 'Costa Rica',
    code: 'CR',
    phone_code: '+506',
    capital: 'San José',
    region: ['NA', 'CAM'],
    subregion: ['CAM'],
    continent_code: 'NA',
    languages: ['es'],
    flag_emoji: '🇨🇷',
    latitude: 9.748917,
    longitude: -83.753428,
  },
  {
    name: "Côte d'Ivoire",
    code: 'CI',
    phone_code: '+225',
    capital: 'Yamoussoukro',
    region: ['AF', 'WAF', 'AU'],
    subregion: ['WAF'],
    continent_code: 'AF',
    languages: ['fr'],
    flag_emoji: '🇨🇮',
    latitude: 7.539989,
    longitude: -5.54708,
  },
  {
    name: 'Croatia',
    code: 'HR',
    phone_code: '+385',
    capital: 'Zagreb',
    region: ['EU', 'SEU', 'EUNION', 'NATO'],
    subregion: ['SEU'],
    continent_code: 'EU',
    languages: ['hr'],
    flag_emoji: '🇭🇷',
    latitude: 45.1,
    longitude: 15.2,
  },
  {
    name: 'Cuba',
    code: 'CU',
    phone_code: '+53',
    capital: 'Havana',
    region: ['NA', 'CAR'],
    subregion: ['CAR'],
    continent_code: 'NA',
    languages: ['es'],
    flag_emoji: '🇨🇺',
    latitude: 21.521757,
    longitude: -77.781167,
  },
  {
    name: 'Cyprus',
    code: 'CY',
    phone_code: '+357',
    capital: 'Nicosia',
    region: ['EU', 'SEU', 'EUNION', 'COMM'],
    subregion: ['SEU'],
    continent_code: 'EU',
    languages: ['el', 'tr', 'hy'],
    flag_emoji: '🇨🇾',
    latitude: 35.126413,
    longitude: 33.429859,
  },
  {
    name: 'Czech Republic',
    code: 'CZ',
    phone_code: '+420',
    capital: 'Prague',
    region: ['EU', 'CEU', 'EUNION', 'NATO', 'OECD'],
    subregion: ['CEU'],
    continent_code: 'EU',
    languages: ['cs', 'sk'],
    flag_emoji: '🇨🇿',
    latitude: 49.817492,
    longitude: 15.472962,
  },

  // D
  {
    name: 'Denmark',
    code: 'DK',
    phone_code: '+45',
    capital: 'Copenhagen',
    region: ['EU', 'NEU', 'EUNION', 'NATO', 'OECD'],
    subregion: ['NEU'],
    continent_code: 'EU',
    languages: ['da'],
    flag_emoji: '🇩🇰',
    latitude: 56.26392,
    longitude: 9.501785,
  },
  {
    name: 'Djibouti',
    code: 'DJ',
    phone_code: '+253',
    capital: 'Djibouti',
    region: ['AF', 'EAF', 'AU', 'AL', 'OIC'],
    subregion: ['EAF'],
    continent_code: 'AF',
    languages: ['fr', 'ar'],
    flag_emoji: '🇩🇯',
    latitude: 11.825138,
    longitude: 42.590275,
  },
  {
    name: 'Dominica',
    code: 'DM',
    phone_code: '+1-767',
    capital: 'Roseau',
    region: ['NA', 'CAR', 'CARICOM', 'COMM'],
    subregion: ['CAR'],
    continent_code: 'NA',
    languages: ['en'],
    flag_emoji: '🇩🇲',
    latitude: 15.414999,
    longitude: -61.370976,
  },
  {
    name: 'Dominican Republic',
    code: 'DO',
    phone_code: '+1-809',
    capital: 'Santo Domingo',
    region: ['NA', 'CAR'],
    subregion: ['CAR'],
    continent_code: 'NA',
    languages: ['es'],
    flag_emoji: '🇩🇴',
    latitude: 18.735693,
    longitude: -70.162651,
  },

  // E
  {
    name: 'Ecuador',
    code: 'EC',
    phone_code: '+593',
    capital: 'Quito',
    region: ['SA', 'AND'],
    subregion: ['SA'],
    continent_code: 'SA',
    languages: ['es'],
    flag_emoji: '🇪🇨',
    latitude: -1.831239,
    longitude: -78.183406,
  },
  {
    name: 'Egypt',
    code: 'EG',
    phone_code: '+20',
    capital: 'Cairo',
    region: ['AF', 'NAF', 'AU', 'AL', 'OIC'],
    subregion: ['NAF'],
    continent_code: 'AF',
    languages: ['ar'],
    flag_emoji: '🇪🇬',
    latitude: 26.820553,
    longitude: 30.802498,
  },
  {
    name: 'El Salvador',
    code: 'SV',
    phone_code: '+503',
    capital: 'San Salvador',
    region: ['NA', 'CAM'],
    subregion: ['CAM'],
    continent_code: 'NA',
    languages: ['es'],
    flag_emoji: '🇸🇻',
    latitude: 13.794185,
    longitude: -88.89653,
  },
  {
    name: 'Equatorial Guinea',
    code: 'GQ',
    phone_code: '+240',
    capital: 'Malabo',
    region: ['AF', 'CAF', 'AU'],
    subregion: ['CAF'],
    continent_code: 'AF',
    languages: ['es', 'fr', 'pt'],
    flag_emoji: '🇬🇶',
    latitude: 1.650801,
    longitude: 10.267895,
  },
  {
    name: 'Eritrea',
    code: 'ER',
    phone_code: '+291',
    capital: 'Asmara',
    region: ['AF', 'EAF', 'AU'],
    subregion: ['EAF'],
    continent_code: 'AF',
    languages: ['ti', 'ar', 'en'],
    flag_emoji: '🇪🇷',
    latitude: 15.179384,
    longitude: 39.782334,
  },
  {
    name: 'Estonia',
    code: 'EE',
    phone_code: '+372',
    capital: 'Tallinn',
    region: ['EU', 'NEU', 'EUNION', 'NATO', 'OECD'],
    subregion: ['NEU'],
    continent_code: 'EU',
    languages: ['et'],
    flag_emoji: '🇪🇪',
    latitude: 58.595272,
    longitude: 25.013607,
  },
  {
    name: 'Eswatini',
    code: 'SZ',
    phone_code: '+268',
    capital: 'Mbabane',
    region: ['AF', 'SAF', 'AU', 'SADC', 'COMM'],
    subregion: ['SAF'],
    continent_code: 'AF',
    languages: ['en', 'ss'],
    flag_emoji: '🇸🇿',
    latitude: -26.522503,
    longitude: 31.465866,
  },
  {
    name: 'Ethiopia',
    code: 'ET',
    phone_code: '+251',
    capital: 'Addis Ababa',
    region: ['AF', 'EAF', 'AU'],
    subregion: ['EAF'],
    continent_code: 'AF',
    languages: ['am'],
    flag_emoji: '🇪🇹',
    latitude: 9.145,
    longitude: 40.489673,
  },

  // F
  {
    name: 'Fiji',
    code: 'FJ',
    phone_code: '+679',
    capital: 'Suva',
    region: ['OC', 'MEL', 'COMM'],
    subregion: ['MEL'],
    continent_code: 'OC',
    languages: ['en', 'fj', 'hi', 'ur'],
    flag_emoji: '🇫🇯',
    latitude: -17.713371,
    longitude: 178.065032,
  },
  {
    name: 'Finland',
    code: 'FI',
    phone_code: '+358',
    capital: 'Helsinki',
    region: ['EU', 'NEU', 'EUNION', 'OECD'],
    subregion: ['NEU'],
    continent_code: 'EU',
    languages: ['fi', 'sv'],
    flag_emoji: '🇫🇮',
    latitude: 61.92411,
    longitude: 25.748151,
  },
  {
    name: 'France',
    code: 'FR',
    phone_code: '+33',
    capital: 'Paris',
    region: ['EU', 'WEU', 'EUNION', 'NATO', 'OECD', 'G7', 'G20'],
    subregion: ['WEU'],
    continent_code: 'EU',
    languages: ['fr'],
    flag_emoji: '🇫🇷',
    latitude: 46.227638,
    longitude: 2.213749,
  }
];
