// Part 3 of the complete world countries list (N-R)
// Following ISO 3166-1 standards with comprehensive regional and language data

import { CountryData } from './country-data';

/**
 * Countries N-R with comprehensive details
 */
export const countriesNR: CountryData[] = [
  // N
  {
    name: 'Namibia',
    code: 'NA',
    phone_code: '+264',
    capital: 'Windhoek',
    region: ['AF', 'SAF', 'AU', 'SADC', 'COMM'],
    subregion: ['SAF'],
    continent_code: 'AF',
    languages: ['en', 'af'],
    flag_emoji: '🇳🇦',
    latitude: -22.95764,
    longitude: 18.49041,
  },
  {
    name: 'Nauru',
    code: 'NR',
    phone_code: '+674',
    capital: 'Yaren',
    region: ['OC', 'MIC', 'COMM'],
    subregion: ['MIC'],
    continent_code: 'OC',
    languages: ['en', 'na'],
    flag_emoji: '🇳🇷',
    latitude: -0.522778,
    longitude: 166.931503,
  },
  {
    name: 'Nepal',
    code: 'NP',
    phone_code: '+977',
    capital: 'Kathmandu',
    region: ['AS', 'SAS'],
    subregion: ['SAS'],
    continent_code: 'AS',
    languages: ['ne'],
    flag_emoji: '🇳🇵',
    latitude: 28.394857,
    longitude: 84.124008,
  },
  {
    name: 'Netherlands',
    code: 'NL',
    phone_code: '+31',
    capital: 'Amsterdam',
    region: ['EU', 'WEU', 'EUNION', 'NATO', 'OECD'],
    subregion: ['WEU'],
    continent_code: 'EU',
    languages: ['nl'],
    flag_emoji: '🇳🇱',
    latitude: 52.132633,
    longitude: 5.291266,
  },
  {
    name: 'New Zealand',
    code: 'NZ',
    phone_code: '+64',
    capital: 'Wellington',
    region: ['OC', 'OECD', 'COMM', 'AUSNZ'],
    subregion: ['OC'],
    continent_code: 'OC',
    languages: ['en', 'mi'],
    flag_emoji: '🇳🇿',
    latitude: -40.900557,
    longitude: 174.885971,
  },
  {
    name: 'Nicaragua',
    code: 'NI',
    phone_code: '+505',
    capital: 'Managua',
    region: ['NA', 'CAM'],
    subregion: ['CAM'],
    continent_code: 'NA',
    languages: ['es'],
    flag_emoji: '🇳🇮',
    latitude: 12.865416,
    longitude: -85.207229,
  },
  {
    name: 'Niger',
    code: 'NE',
    phone_code: '+227',
    capital: 'Niamey',
    region: ['AF', 'WAF', 'AU', 'OIC'],
    subregion: ['WAF'],
    continent_code: 'AF',
    languages: ['fr'],
    flag_emoji: '🇳🇪',
    latitude: 17.607789,
    longitude: 8.081666,
  },
  {
    name: 'Nigeria',
    code: 'NG',
    phone_code: '+234',
    capital: 'Abuja',
    region: ['AF', 'WAF', 'AU', 'COMM', 'OIC', 'OPEC'],
    subregion: ['WAF'],
    continent_code: 'AF',
    languages: ['en'],
    flag_emoji: '🇳🇬',
    latitude: 9.081999,
    longitude: 8.675277,
  },
  {
    name: 'North Korea',
    code: 'KP',
    phone_code: '+850',
    capital: 'Pyongyang',
    region: ['AS', 'EAS'],
    subregion: ['EAS'],
    continent_code: 'AS',
    languages: ['ko'],
    flag_emoji: '🇰🇵',
    latitude: 40.339852,
    longitude: 127.510093,
  },
  {
    name: 'North Macedonia',
    code: 'MK',
    phone_code: '+389',
    capital: 'Skopje',
    region: ['EU', 'SEU', 'NATO'],
    subregion: ['SEU'],
    continent_code: 'EU',
    languages: ['mk'],
    flag_emoji: '🇲🇰',
    latitude: 41.608635,
    longitude: 21.745275,
  },
  {
    name: 'Norway',
    code: 'NO',
    phone_code: '+47',
    capital: 'Oslo',
    region: ['EU', 'NEU', 'NATO', 'OECD'],
    subregion: ['NEU'],
    continent_code: 'EU',
    languages: ['no', 'nb', 'nn'],
    flag_emoji: '🇳🇴',
    latitude: 60.472024,
    longitude: 8.468946,
  },

  // O
  {
    name: 'Oman',
    code: 'OM',
    phone_code: '+968',
    capital: 'Muscat',
    region: ['AS', 'WAS', 'AL', 'GCC', 'OIC'],
    subregion: ['WAS'],
    continent_code: 'AS',
    languages: ['ar'],
    flag_emoji: '🇴🇲',
    latitude: 21.512583,
    longitude: 55.923255,
  },

  // P
  {
    name: 'Pakistan',
    code: 'PK',
    phone_code: '+92',
    capital: 'Islamabad',
    region: ['AS', 'SAS', 'COMM', 'OIC'],
    subregion: ['SAS'],
    continent_code: 'AS',
    languages: ['en', 'ur'],
    flag_emoji: '🇵🇰',
    latitude: 30.375321,
    longitude: 69.345116,
  },
  {
    name: 'Palau',
    code: 'PW',
    phone_code: '+680',
    capital: 'Ngerulmud',
    region: ['OC', 'MIC'],
    subregion: ['MIC'],
    continent_code: 'OC',
    languages: ['en'],
    flag_emoji: '🇵🇼',
    latitude: 7.51498,
    longitude: 134.58252,
  },
  {
    name: 'Palestine',
    code: 'PS',
    phone_code: '+970',
    capital: 'Ramallah',
    region: ['AS', 'WAS', 'AL', 'OIC'],
    subregion: ['WAS'],
    continent_code: 'AS',
    languages: ['ar'],
    flag_emoji: '🇵🇸',
    latitude: 31.952162,
    longitude: 35.233154,
  },
  {
    name: 'Panama',
    code: 'PA',
    phone_code: '+507',
    capital: 'Panama City',
    region: ['NA', 'CAM'],
    subregion: ['CAM'],
    continent_code: 'NA',
    languages: ['es'],
    flag_emoji: '🇵🇦',
    latitude: 8.537981,
    longitude: -80.782127,
  },
  {
    name: 'Papua New Guinea',
    code: 'PG',
    phone_code: '+675',
    capital: 'Port Moresby',
    region: ['OC', 'MEL', 'COMM'],
    subregion: ['MEL'],
    continent_code: 'OC',
    languages: ['en'],
    flag_emoji: '🇵🇬',
    latitude: -6.314993,
    longitude: 143.95555,
  },
  {
    name: 'Paraguay',
    code: 'PY',
    phone_code: '+595',
    capital: 'Asunción',
    region: ['SA', 'MERCOSUR'],
    subregion: ['SA'],
    continent_code: 'SA',
    languages: ['es', 'gn'],
    flag_emoji: '🇵🇾',
    latitude: -23.442503,
    longitude: -58.443832,
  },
  {
    name: 'Peru',
    code: 'PE',
    phone_code: '+51',
    capital: 'Lima',
    region: ['SA', 'AND'],
    subregion: ['SA'],
    continent_code: 'SA',
    languages: ['es', 'qu', 'ay'],
    flag_emoji: '🇵🇪',
    latitude: -9.189967,
    longitude: -75.015152,
  },
  {
    name: 'Philippines',
    code: 'PH',
    phone_code: '+63',
    capital: 'Manila',
    region: ['AS', 'SEA', 'ASEAN'],
    subregion: ['SEA'],
    continent_code: 'AS',
    languages: ['en', 'tl'],
    flag_emoji: '🇵🇭',
    latitude: 12.879721,
    longitude: 121.774017,
  },
  {
    name: 'Poland',
    code: 'PL',
    phone_code: '+48',
    capital: 'Warsaw',
    region: ['EU', 'CEU', 'EUNION', 'NATO', 'OECD'],
    subregion: ['CEU'],
    continent_code: 'EU',
    languages: ['pl'],
    flag_emoji: '🇵🇱',
    latitude: 51.919438,
    longitude: 19.145136,
  },
  {
    name: 'Portugal',
    code: 'PT',
    phone_code: '+351',
    capital: 'Lisbon',
    region: ['EU', 'SEU', 'EUNION', 'NATO', 'OECD'],
    subregion: ['SEU'],
    continent_code: 'EU',
    languages: ['pt'],
    flag_emoji: '🇵🇹',
    latitude: 39.399872,
    longitude: -8.224454,
  },

  // Q
  {
    name: 'Qatar',
    code: 'QA',
    phone_code: '+974',
    capital: 'Doha',
    region: ['AS', 'WAS', 'AL', 'GCC', 'OIC', 'OPEC'],
    subregion: ['WAS'],
    continent_code: 'AS',
    languages: ['ar'],
    flag_emoji: '🇶🇦',
    latitude: 25.354826,
    longitude: 51.183884,
  },

  // R
  {
    name: 'Romania',
    code: 'RO',
    phone_code: '+40',
    capital: 'Bucharest',
    region: ['EU', 'EEU', 'EUNION', 'NATO'],
    subregion: ['EEU'],
    continent_code: 'EU',
    languages: ['ro'],
    flag_emoji: '🇷🇴',
    latitude: 45.943161,
    longitude: 24.96676,
  },
  {
    name: 'Russia',
    code: 'RU',
    phone_code: '+7',
    capital: 'Moscow',
    region: ['EU', 'EEU', 'AS', 'CIS', 'BRICS', 'G20'],
    subregion: ['EEU'],
    continent_code: 'EU', // Note: Russia spans Europe and Asia
    languages: ['ru'],
    flag_emoji: '🇷🇺',
    latitude: 61.52401,
    longitude: 105.318756,
  },
  {
    name: 'Rwanda',
    code: 'RW',
    phone_code: '+250',
    capital: 'Kigali',
    region: ['AF', 'EAF', 'AU', 'COMM'],
    subregion: ['EAF'],
    continent_code: 'AF',
    languages: ['rw', 'en', 'fr'],
    flag_emoji: '🇷🇼',
    latitude: -1.940278,
    longitude: 29.873888,
  }
];
